const sequelize = require('../config/db');
const Ticket = require('../models/Ticket');
const User = require('../models/User');
const TicketShare = require('../models/TicketShare');
const { Op } = require('sequelize');

// Set up associations for test environment
User.hasMany(Ticket, { foreignKey: 'creatorId', as: 'CreatedTickets' });
User.hasMany(Ticket, { foreignKey: 'currentAssigneeId', as: 'AssignedTickets' });
Ticket.belongsTo(User, { foreignKey: 'creatorId', as: 'Creator' });
Ticket.belongsTo(User, { foreignKey: 'currentAssigneeId', as: 'Assignee' });

Ticket.hasMany(TicketShare, { foreignKey: 'ticketId' });
TicketShare.belongsTo(Ticket, { foreignKey: 'ticketId' });
TicketShare.belongsTo(User, { foreignKey: 'userId' });

async function test() {
  try {
    await sequelize.authenticate();
    console.log('Database connected.');

    // We select a non-executive user (e.g., employee with id = 5)
    const user = await User.findByPk(5);
    if (!user) {
      console.log('User 5 not found.');
      return;
    }
    console.log(`Mocking query for User: ${user.fullName} (ID: ${user.id}, Role: ${user.role})`);

    // Let's print out the SQL query generated by Sequelize
    const tickets = await Ticket.findAll({
      where: {
        [Op.or]: [
          { creatorId: user.id },
          { currentAssigneeId: user.id },
          { '$TicketShares.userId$': user.id }
        ]
      },
      include: [
        { model: User, as: 'Creator', attributes: ['fullName', 'role'] },
        { model: User, as: 'Assignee', attributes: ['fullName', 'role'] },
        { model: TicketShare, include: [{ model: User, attributes: ['fullName'] }] }
      ],
      logging: console.log // Print SQL query!
    });

    console.log(`Found ${tickets.length} tickets for this user.`);
  } catch (error) {
    console.error(error);
  } finally {
    await sequelize.close();
  }
}

test();
